Adding NuGet support
x64dbg/DotX64Dbg pull request #28
Opened 2021-11-03 04:16 UTC by Guila767

### NuGet support?
I added rough support for NuGet dependencies in the Csharp projects. Currently, it's capable of searching for the 'PackageReference' tag in the project, automatically resolving the references via NuGet.
### How it's done:
First, it tries to find the package locally in the packages cache, otherwise, it creates a local NuGet repository to store the dependencies packages that will be downloaded and used for future builds.
### Notes:
It requires more testing and has room for improvements in the code.

2021-11-03 14:10 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.Builder.cs
> +            string csProjctPath = System.IO.Path.Combine(plugin.Path, plugin.Info.Name + ".csproj");
I think it would be better to use the json file for dependencies since the csproj is auto generated and shouldn't be shipped with plugins.

2021-11-03 14:12 UTC, ZehMatt requested changes
Thanks for the PR, this is indeed a very nice thing to have and I've been wondering before on how to do it. I left a comment regarding dependency management.

2021-11-03 16:05 UTC, Guila767 commented on src/Dotx64Managed/Plugins.Builder.cs
> +            string csProjctPath = System.IO.Path.Combine(plugin.Path, plugin.Info.Name + ".csproj");
Yeah, that's true. I think a possible approach is, any dependency added to the local csproj needs to be 'synced' with the json file and the same when creating the csproj.

2021-11-03 16:14 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.Builder.cs
> +            string csProjctPath = System.IO.Path.Combine(plugin.Path, plugin.Info.Name + ".csproj");
We could probably do that in the future.

2021-11-04 20:11 UTC, ZehMatt commented
Please rebase instead of merging, I would like to try to keep the history clean.

2021-11-04 20:46 UTC, Guila767 commented
I added a simple synchronization in dependencies between the plugin JSON and the csproj. When the plugin watcher event is triggered, before compiling the changes, if any, it checks for changes in the dependencies in the csproj and adds to the plugin JSON. I needed to adopt a convention when naming the packages in the JSON file, I end up using the standard from DotNet framework names: `<Framework.Name>,Version=v<0.0.0>`.

Now the plugin config JSON file looks like this:
```json
{
  "Name": "Example Plugin",
  "Description": "Basic example plugin.",
  "Version": "1.0.0",
  "Author": "x64Dbg",
  "Website": "http://github.com/x64Dbg",
  "Dependencies": [
    "System.Console.dll",
    "Newtonsoft.Json,Version=v13.0.1"
  ],
  "Settings": {
    "Test": true
  }
}
```

2021-11-04 20:53 UTC, ZehMatt commented
Looks reasonable to me.

2021-11-04 21:35 UTC, ZehMatt requested changes
I gave it a run and there seems to be a problem with plugins that don't specify any dependencies. Also left a few comments regarding code. As for the csproj synchronization I think it would be better to have in this PR just the basics to have NuGet working with the json alone and do another PR where the csproj synchronization is done to make testing also a bit easier.

2021-11-04 21:35 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.Builder.cs
> +            List<string> references = new(plugin.Info.Dependencies);
```plugin.Info.Dependencies``` can be null when the json does not specify anything.

2021-11-04 21:35 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.DependencyManager.cs
> +                if (plugin.Info is null || plugin.Info!.Dependencies.Length == 0)
Dependencies can be null

2021-11-04 21:35 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.DependencyManager.cs
> +            //static readonly string NupkgExtension = ".nupkg";
If its not used it should be deleted.

2021-11-04 21:35 UTC, ZehMatt commented on src/Dotx64Managed/Plugins.Builder.cs
> +        [Obsolete]
If its actually obsolete we shouldn't have it.

2021-11-05 16:25 UTC, ZehMatt commented
I've tested the latest commit and it seems to be working. I think it might be best to have a ```.nuget``` folder or something to avoid cluttering the plugins folder, Dotx64Dbg unfortunately adds quite a few things already. Another thing I noticed is that when I modify the json file the csproj is not updated instead the json is being overwritten once code changes are detected.

2021-11-05 17:21 UTC, Guila767 commented
> I've tested the latest commit and it seems to be working. I think it might be best to have a `.nuget` folder or something to avoid cluttering the plugins folder, Dotx64Dbg unfortunately adds quite a few things already. Another thing I noticed is that when I modify the json file the csproj is not updated instead the json is being overwritten once code changes are detected.

About this last issue, I will follow your advice and drop the Csproj sync for this PR. When this feature reaches a more mature state I will try opening a new PR, and this should address this issue. But yeah, NuGet has quite of dependencies, I will see what I can do.

2021-11-05 21:01 UTC, ZehMatt commented
To be fair the experience so far is not bad and I was actually quite surprised to how well this actually worked. Considering the Nuget part pretty much works already its just a bit of code cleanup. The PR is highly appreciated, thanks for your effort.

2021-11-06 02:25 UTC, Guila767 commented
Commit: b1245008379613f733850a36846da43978aded1e
With this commit everything is more or less working now, as far I tested.

Commit: 021916570fc09870c21ca0878530d807be8e6f61
I tried to address the problem with the plugin folder being cluttered. After a bit of research, I figure out a way to move all the NuGet dependencies to a subfolder in the build output, so I modified the Csproj to the NuGet dependencies get moved to a `.nuget` dir, and now all the 'moved assemblies' need to be resolved at run time. It's probably not an elegant solution, mostly because I didn't find any documentation about it. I did a bit of testing and looks to be working, I used the '_Process Hacker_' to look at the loaded modules and they all appear to be loaded from the `.nuget` dir.

So in my conclusion, the commit 021916570fc09870c21ca0878530d807be8e6f61 needs to be reviewed if it is a valid solution, otherwise, I don't know a way to fix this specific problem

2021-11-06 14:16 UTC, ZehMatt approved these changes
Big thanks again, I've tested it and its working as expected, there is one issue that is unrelated to your changes which is when I add a new dependency in the json while x64dbg is running it won't rebuild the code, that is something I will fix after I merge this PR. Code wise everything looks good to me.

2021-11-06 14:17 UTC, ZehMatt commented
Before I merge it, is there anything on your side you would like to change before doing so?

2021-11-06 14:33 UTC, Guila767 commented
For now, I think that's it. Thanks for your support!

2021-11-06 14:41 UTC, merged