Added support for menu icons
x64dbg/DotX64Dbg pull request #47
Opened 2021-11-19 20:23 UTC by Guila767

I added a simple binding for setting icons in the menus. 
The resources added to the project are only suggestions/placeholders.

### Preview:
![image](https://user-images.githubusercontent.com/31376051/142686785-3b61a22e-d6dd-4cda-8f79-57302b16fcb9.png)

2021-11-20 18:05 UTC, ZehMatt commented
While technically I'm in favor to have this but I'm not a huge fan about the black background, is there a way to add transparency support for pngs/icos?

2021-11-21 03:16 UTC, Guila767 commented
Yes, it's possible. Accessing the DI bitmap bits from a handle returned by `Bitmap::GetHbitmap()` makes the alpha channel data get lost. The alpha channel and a miss configuration on the `BITMAPV5HEADER` make the transparency of the icons not work. I'm already working on the solution.

2021-11-21 05:58 UTC, Guila767 commented
### Menu icons with transparency
![Preview](https://user-images.githubusercontent.com/31376051/142751461-6ac01e7d-1d13-4e27-ac78-2e0b3fbaad62.png)

2021-11-21 17:52 UTC, ZehMatt requested changes
Without the black background thats way better, I left some comments.

2021-11-21 17:52 UTC, ZehMatt commented on src/Bindings/UI.cpp
> +                }
I think this should be moved into a function that gets the image data resulting std::unique_ptr<uint8_t[]>

2021-11-21 17:52 UTC, ZehMatt commented on src/Bindings/UI.cpp
> +                }
Duplicate code, see above.

2021-11-21 21:48 UTC, Guila767 commented on src/Bindings/UI.cpp
> +                }
These are bindings for two distinct functions. Do you mean we should move the `ICONDATA` initialization to another procedure?

2021-11-21 21:57 UTC, ZehMatt commented on src/Bindings/UI.cpp
> +                }
That block just loads the image data, it could be a function like ```static std::vector<uint8_t> GetImageData(System::Image^ img)```

Then after calling this you just need to assign the resulting pointer and size to ICONDATA

2021-11-21 22:52 UTC, ZehMatt approved these changes
Nice, I like it. Regarding the icons, did you create them? I would like to avoid any copyright claims regarding legal concerns, also I'm asking if you are the author of the logo would you like to sponsor it to be generally used for this project?

2021-11-21 23:46 UTC, Guila767 commented
Well, I created the logo based on the x64Dbg logo, but the other icons are slightly modified versions from the [visual studio image library](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2022), and as far I know, it's free to use then. If this is not a problem, I don't mind letting them for this project

2021-11-22 00:28 UTC, ZehMatt commented
Well I guess this will be the official logo from now on then, thanks!

2021-11-22 00:28 UTC, merged